// This file was generated by Prisma, and assumes you have installed the following:
// bun add --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    // Direct PostgreSQL connection URL
    url: process.env['DATABASE_URL'],
    // For Prisma Accelerate, use accelerateUrl:
    // url: process.env['DATABASE_URL'], // prisma+postgres://...
  },
});
